Add failure condition if renv cache required but none available

diff --git a/.github/workflows/docker_build_deploy.yml b/.github/workflows/docker_build_deploy.yml
--- a/.github/workflows/docker_build_deploy.yml
+++ b/.github/workflows/docker_build_deploy.yml
@@ -82,6 +82,7 @@ jobs:
           Rscript /home/rstudio/.workbench/setup_lesson_deps.R
 
       - name: Restore renv from cache
+        id: restore-renv-cache
         uses: actions/cache@v4
         if: env.RENV_EXISTS == 'true'
         with:
@@ -91,7 +92,7 @@ jobs:
             ${{ runner.os }}-${{ inputs.cache-version }}-renv-
 
       - name: Restore renv Dependencies
-        if: env.RENV_EXISTS == 'true'
+        if: env.RENV_EXISTS == 'true' && steps.restore-renv-cache.outputs.cache-hit == 'true'
         run: |
           lsn_path <- fs::path("/home/rstudio/lesson")
           renv::load(project = lsn_path)
@@ -99,6 +100,12 @@ jobs:
           renv_lock <- renv::paths$lockfile(project = lsn_path)
           renv::restore(project = lsn_path, library = renv_lib, lockfile = renv_lock, prompt = FALSE)
         shell: Rscript {0}
+
+      - name: Fail on renv cache miss
+        if: env.RENV_EXISTS == 'true' && steps.restore-renv-cache.outputs.cache-hit != 'true'
+        run: |
+          echo "❌ renv cache required but none available. Please run the 'DOCKER Apply Package Cache' workflow."
+          exit 1
 
       - name: Run Container and Build Site
         run: |
